INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Mayson', 'Britt', 48, 07111);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Isabell', 'Guzman', 20, 60048);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Umaiza', 'Flynn', 75, 37040);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Zaine', 'Hanson', 51, 13090);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Kajus', 'Wallace', 98, 23139);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Ava-Rose', 'Berg', 65, 02072);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Gina', 'Burnett', 72, 21009);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Pawel', 'Duke', 34, 08360);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Christy', 'Meza', 25, 28079);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Manav', 'Watt', 75, 07747);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Marc', 'Hogg', 56, 60440);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Jarrad', 'Heath', 45, 28645);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Ned', 'Rosario', 85, 13440);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Gemma', 'Hastings', 82, 21220);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Aneurin', 'Mooney', 36, 29501);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Jaye', 'Butt', 75, 29910);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Cheyenne', 'Lang', 55, 45365);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Lillie-Mai', 'Mata', 66, 49009);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Faith', 'Hume', 42, 49120);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Saffa', 'Oconnor', 65, 33056);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Dante', 'Horner', 78, 60089);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Herbie', 'Gillespie', 34, 20705);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Francesco', 'Sims', 58, 46321);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Blade', 'Rojas', 42, 07076);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Mira', 'Brooks', 12, 64151);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Alima', 'Mayer', 85, 06082);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Brody', 'Keith', 18, 32174);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Rajan', 'Sparks', 63, 12010);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Ralph', 'Ponce', 74, 11003);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Annabelle', 'Hunter', 49, 07042);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Kaelan', 'Valenzuela', 35, 60067);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Zunairah', 'Humphries', 85, 64151);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Desiree', 'Salazar', 52, 08753);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Jeanette', 'Cullen', 59, 07030);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Lyla', 'Mason', 25, 56001);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Misty', 'Scott', 42, 08302);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Amy-Louise', 'Atkins', 30, 06511);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Antonio', 'Davis', 70, 74403);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Tehya', 'Griffin', 84, 02368);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Montgomery', 'Peck', 73, 38106);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Diane', 'Brock', 20, 08094);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Yolanda', 'Fox', 39, 01960);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Shivam', 'Vance', 44, 47302);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Leonie', 'Chase', 22, 50265);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Kierran', 'Johnson', 9, 45356);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Scarlett-Rose', 'Whittington', 45, 08861);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Jadene', 'Chavez', 36, 32034);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Mujtaba', 'Parkinson', 88, 08302);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Nel', 'Devine', 96, 74403);
INSERT INTO persons (firstName, lastName, age, postal) VALUES ('Chase', 'Cortez', 80, 38106);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Sickle cell disease','Huvudvärk', 'Hosta', 'Andnöd', 3);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Deafblindness','Svullen fot', 'Cirkelgång', 'Förlorad balans', 3);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Bile duct cancer ','Magsmärta', 'Vomering', 'Svullnad', 4);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Flu','Ihopfallnad', 'Bruten arm', 'Blåmärke', 3);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Acne','Ryckig gång', 'Snabbt tal', 'Envishet', 1);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Otitis externa','Huvudvärk', 'Hosta', 'Andnöd', 2);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Heart failure','Svullen fot', 'Cirkelgång', 'Förlorad balans', 5);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Restless legs syndrome ','Magsmärta', 'Vomering', 'Svullnad', 3);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Type 2 diabetes','Ihopfallnad', 'Bruten arm', 'Blåmärke', 3);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Malaria','Ryckig gång', 'Snabbt tal', 'Envishet', 5);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Irritable hip','Huvudvärk', 'Hosta', 'Andnöd', 2);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Personality disorder','Svullen fot', 'Cirkelgång', 'Förlorad balans', 3);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Threadworms ','Magsmärta', 'Vomering', 'Svullnad', 4);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Dehydration','Ihopfallnad', 'Bruten arm', 'Blåmärke', 1);
INSERT INTO pathosis (name, symptom_one, symptom_two, symptom_three, mortality) VALUES ('Psoriasis','Ryckig gång', 'Snabbt tal', 'Envishet', 2);
